apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email'
    repeatInterval: 30m
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      repeatInterval: 10m
  receivers:
  - name: 'email'
    emailConfigs:
    - to: '{$GMAIL}'
      from: '{$GMAIL}'
      smarthost: 'smtp.gmail.com:587'
      authUsername: '{$GMAIL}'
      authIdentity: '{$GMAIL}'
      authPassword:
       name: gmail-auth
       key: password